/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Eleventh.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Eleventh.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Eleven_Front_Entrance_Baked.geometry}
        material={materials.Eleventh_Final_Actual_Baked}
        position={[4.568, 6.749, -38.719]}
        rotation={[0, Math.PI / 2, 0]}
      />
    </group>
  );
}

useGLTF.preload("/Eleventh.glb");
