/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Ninth.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Ninth.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ninth_DemosHub_Baked.geometry} material={materials.Ninth_real_actual_Baked} position={[6.136, 9.285, -48.469]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Ninth_DesignerSpotlight_Baked.geometry} material={materials.Ninth_real_actual_Baked} position={[9.538, 9.285, -48.469]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Ninth_DeveloperSpotlight_Baked.geometry} material={materials.Ninth_real_actual_Baked} position={[12.806, 9.285, -48.469]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Ninth_Paper_Baked.geometry} material={materials.Ninth_real_actual_Baked} position={[6.122, 6.808, -35.966]} />
      <mesh geometry={nodes.Ninth_TheCollective_Baked.geometry} material={materials.Ninth_real_actual_Baked} position={[-0.457, 9.285, -48.469]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Ninth_Webzibition_Baked.geometry} material={materials.Ninth_real_actual_Baked} position={[2.778, 9.285, -48.469]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Ninth.glb')
