/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 waterfall.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/waterfall.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Waterfall.geometry} material={nodes.Waterfall.material} position={[32.444, 69.171, -73.738]} rotation={[Math.PI, -1.514, Math.PI]} />
    </group>
  )
}

useGLTF.preload('/waterfall.glb')
