/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Background.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { convertMaterialsToBasic } from "../utils/convertToBasic";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/Background.glb");

  const newMaterials = convertMaterialsToBasic(materials);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.background.geometry}
        material={newMaterials.background}
        position={[-273.311, 66.468, -184.652]}
        rotation={[Math.PI / 2, 0, -0.765]}
        scale={278.189}
      />
    </group>
  );
}

useGLTF.preload("/models/Background.glb");
