/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Background.glb 
*/

import React from "react";
import { useGLTF, Instances, Instance } from "@react-three/drei";
import { convertMaterialsToBasic } from "../utils/convertToBasic";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/Background.glb");

  const newMaterials = convertMaterialsToBasic(materials);
  return (
    <Instances
      limit={3}
      geometry={nodes.background.geometry}
      material={newMaterials.background}
      {...props}
    >
      {/* First instance */}
      <Instance
        position={[-170.311, 66.468, -124.652]}
        rotation={[Math.PI / 2, 0, -0.765]}
        scale={205.189}
      />

      {/* Second instance */}
      <Instance
        position={[190.311, 30.468, -114.652]}
        rotation={[Math.PI / 2, 0, 0.5]}
        scale={200}
      />
    </Instances>
  );
}

useGLTF.preload("/models/Background.glb");
