/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Eighth.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useGLTFWithKTX2 } from "../utils/useGLTFWithKTX2";
import { convertMaterialsToBasic } from "../utils/convertToBasic";

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2("/models/Eighth.glb");
  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Eighth_Baked.geometry}
        material={newMaterials.Eighth_Baked}
        position={[-5.2, 9.818, -23.394]}
        rotation={[0, -0.091, 0]}
      />
      <mesh
        geometry={nodes.Eighth_Tree_Baked.geometry}
        material={newMaterials.Eighth_Baked}
        position={[29.885, -1.852, -2.243]}
        rotation={[0.093, 0.914, -0.048]}
      />
    </group>
  );
}
