/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Ninth.glb 
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTFWithKTX2 } from "../utils/useGLTFWithKTX2";
import { convertMaterialsToBasic } from "../utils/convertToBasic";
import * as THREE from "three";
import { useModalStore } from "../../stores/useModalStore";

export default function Model({ progress = 0, pulseIntensity = 0, ...props }) {
  const { nodes, materials } = useGLTFWithKTX2("/models/Ninth.glb");
  const [hoveredMesh, setHoveredMesh] = useState(null);
  const { openModal, setModalID, isModalOpen } = useModalStore();

  const newMaterials = convertMaterialsToBasic(materials);

  const baseMaterial = newMaterials["Ninth_Final_Baked"].clone();

  const brightHoveredMaterial = newMaterials["Ninth_Final_Baked"].clone();
  brightHoveredMaterial.color = new THREE.Color(2.5, 2.5, 2.5);

  const pulsingMaterial = newMaterials["Ninth_Final_Baked"].clone();

  const getMaterial = (elementID, progressRange) => {
    if (hoveredMesh === elementID && progress >= 0.399 && progress <= 0.6)
      return brightHoveredMaterial;

    const [min, max] = progressRange;
    if (progress >= min && progress <= max) {
      const pulseColor = 1 + pulseIntensity * 1.5;
      pulsingMaterial.color.setRGB(pulseColor, pulseColor, pulseColor);
      return pulsingMaterial;
    }
    return baseMaterial;
  };

  useEffect(() => {
    if (progress >= 0.399 && progress <= 0.6)
      document.body.style.cursor = hoveredMesh ? "pointer" : "auto";
  }, [hoveredMesh]);

  const handleClick = (elementID) => {
    if (progress <= 0.399 || progress >= 0.6 || isModalOpen) return;
    openModal();
    setModalID(elementID);
  };

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Ninth_Codrops_Baked.geometry}
        material={getMaterial("codrops", [0.399, 0.6])}
        onPointerOver={() => setHoveredMesh("codrops")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={() => {
          handleClick("codrops");
        }}
        position={[6.136, 9.285, -48.469]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Ninth_CSSTricks_Baked.geometry}
        material={getMaterial("csstricks", [0.399, 0.6])}
        onPointerOver={() => setHoveredMesh("csstricks")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={() => {
          handleClick("csstricks");
        }}
        position={[-0.457, 9.285, -48.469]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Ninth_ThreejsJourney_Baked.geometry}
        material={getMaterial("threejsjourney", [0.399, 0.6])}
        onPointerOver={() => setHoveredMesh("threejsjourney")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={() => {
          handleClick("threejsjourney");
        }}
        position={[2.778, 9.285, -48.469]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Ninth_Blender_Baked.geometry}
        material={getMaterial("blender", [0.399, 0.6])}
        onPointerOver={() => setHoveredMesh("blender")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={() => {
          handleClick("blender");
        }}
        position={[12.806, 9.285, -48.469]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Ninth_Threejs_Baked.geometry}
        material={getMaterial("threejs", [0.399, 0.6])}
        onPointerOver={() => setHoveredMesh("threejs")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={() => {
          handleClick("threejs");
        }}
        position={[9.538, 9.285, -48.469]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Ninth_Paper_Baked.geometry}
        material={newMaterials["Ninth_Final_Baked"]}
        position={[6.122, 6.808, -35.966]}
      />
    </group>
  );
}
